# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
weather_df = pd.read_csv('../output_data/Cities.csv')
weather_df

,City,Country,Temperature,Humidity,Cloudiness,Windspeed,Latitude,Longitude,Date
0,solotvyn,UA,53.26,92,6,3.74,48.7021,24.4221,1655525591
1,richards bay,ZA,53.29,58,0,6.96,-28.7830,32.0377,1655525591
2,yulara,AU,70.45,30,67,11.59,-25.2406,130.9889,1655525328
3,potsdam,DE,70.29,80,97,7.61,52.3989,13.0657,1655525592
4,san policarpo,PH,85.80,71,30,9.71,12.1791,125.5072,1655525593
...,...,...,...,...,...,...,...,...,...
552,balykshi,KZ,69.80,78,0,8.95,47.0667,51.8667,1655525801
553,morant bay,JM,80.22,84,100,6.64,17.8815,-76.4093,1655525801
554,kangaatsiaq,GL,33.85,96,90,2.89,68.3065,-53.4641,1655525802
555,constitucion,CL,50.27,83,97,7.23,-35.3333,-72.4167,1655525802
556,port-cartier,CA,55.74,98,98,6.11,50.0334,-66.8654,1655525802

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
# Configure gmaps
gmaps.configure(api_key=g_key)

In [4]:
# Define variables locations and weight
locations = weather_df[['Latitude', 'Longitude']]
humidity = weather_df['Humidity']

In [5]:
# Display heatmap
fig = gmaps.figure()
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=100, point_radius=1)

fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [6]:
# Filter dataframe with ideal weather conditons
ideal_weather = weather_df.loc[(weather_df['Temperature'] >= 70) & (weather_df['Temperature'] <= 80) & (weather_df['Windspeed'] <= 10) & (weather_df['Cloudiness'] == 0)]

ideal_weather

,City,Country,Temperature,Humidity,Cloudiness,Windspeed,Latitude,Longitude,Date
19,reidsville,US,70.48,100,0,0.00,36.3549,-79.6645,1655525598
37,saint-denis,FR,73.18,59,0,4.61,48.9167,2.3333,1655525522
40,souillac,MU,71.35,71,0,2.84,-20.5167,57.5167,1655525604
61,mahebourg,MU,72.25,73,0,1.07,-20.4081,57.7000,1655525612
63,bethel,US,73.76,74,0,3.44,41.3712,-73.4140,1655525613
96,quatre cocos,MU,72.09,74,0,1.59,-20.2078,57.7625,1655525625
174,bambous virieux,MU,72.21,74,0,0.47,-20.3428,57.7575,1655525655
185,gat,IL,74.39,100,0,3.00,31.6100,34.7642,1655525660
201,awjilah,LY,74.35,50,0,5.93,29.1081,21.2869,1655525667
208,jalu,LY,75.06,46,0,6.17,29.0331,21.5482,1655525669
233,conde,BR,71.06,100,0,3.44,-7.2597,-34.9075,1655525678
242,urumqi,CN,74.35,29,0,4.47,43.8010,87.6005,1655525682
265,hun,LY,70.63,54,0,3.60,29.1268,15.9477,1655525694
266,middle island,US,75.87,60,0,9.22,40.8843,-72.9373,1655525694
268,kerman,IR,79.72,16,0,3.62,30.2832,57.0788,1655525695
287,cap malheureux,MU,72.46,75,0,3.00,-19.9842,57.6142,1655525703
318,laurel,US,78.48,55,0,6.91,39.0993,-76.8483,1655525713
319,hamilton,US,74.64,58,0,9.22,39.1834,-84.5333,1655525421
325,nador,MA,75.45,78,0,4.61,35.1740,-2.9287,1655525715
336,natal,BR,75.42,94,0,5.75,-5.7950,-35.2094,1655525719
341,shahreza,IR,76.30,21,0,4.34,32.0339,51.8794,1655525721
349,russell,US,79.12,88,0,0.00,32.3502,-85.1999,1655525724
353,ajdabiya,LY,71.10,74,0,8.39,30.7554,20.2263,1655525726
372,saint anthony,US,70.93,70,0,0.00,45.0205,-93.2180,1655525733
379,corinto,GR,75.88,60,0,2.82,37.9407,22.9573,1655525735
387,mira,IT,72.10,75,0,3.44,45.4358,12.1348,1655525738
413,mao,ES,72.16,94,0,3.44,39.8885,4.2658,1655525749
441,bafra,TR,71.82,68,0,2.91,41.5678,35.9069,1655525760
444,grand gaube,MU,72.37,75,0,3.00,-20.0064,57.6608,1655525762

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [7]:
# Store variabled named hotel_df and add hotel name into dataframe
hotel_df = ideal_weather
hotel_df['Hotel Name'] = ""
hotel_df

c:\Users\ronfu\anaconda3\envs\bootcamp\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,City,Country,Temperature,Humidity,Cloudiness,Windspeed,Latitude,Longitude,Date,Hotel Name
19,reidsville,US,70.48,100,0,0.00,36.3549,-79.6645,1655525598,
37,saint-denis,FR,73.18,59,0,4.61,48.9167,2.3333,1655525522,
40,souillac,MU,71.35,71,0,2.84,-20.5167,57.5167,1655525604,
61,mahebourg,MU,72.25,73,0,1.07,-20.4081,57.7000,1655525612,
63,bethel,US,73.76,74,0,3.44,41.3712,-73.4140,1655525613,
96,quatre cocos,MU,72.09,74,0,1.59,-20.2078,57.7625,1655525625,
174,bambous virieux,MU,72.21,74,0,0.47,-20.3428,57.7575,1655525655,
185,gat,IL,74.39,100,0,3.00,31.6100,34.7642,1655525660,
201,awjilah,LY,74.35,50,0,5.93,29.1081,21.2869,1655525667,
208,jalu,LY,75.06,46,0,6.17,29.0331,21.5482,1655525669,
233,conde,BR,71.06,100,0,3.44,-7.2597,-34.9075,1655525678,
242,urumqi,CN,74.35,29,0,4.47,43.8010,87.6005,1655525682,
265,hun,LY,70.63,54,0,3.60,29.1268,15.9477,1655525694,
266,middle island,US,75.87,60,0,9.22,40.8843,-72.9373,1655525694,
268,kerman,IR,79.72,16,0,3.62,30.2832,57.0788,1655525695,
287,cap malheureux,MU,72.46,75,0,3.00,-19.9842,57.6142,1655525703,
318,laurel,US,78.48,55,0,6.91,39.0993,-76.8483,1655525713,
319,hamilton,US,74.64,58,0,9.22,39.1834,-84.5333,1655525421,
325,nador,MA,75.45,78,0,4.61,35.1740,-2.9287,1655525715,
336,natal,BR,75.42,94,0,5.75,-5.7950,-35.2094,1655525719,
341,shahreza,IR,76.30,21,0,4.34,32.0339,51.8794,1655525721,
349,russell,US,79.12,88,0,0.00,32.3502,-85.1999,1655525724,
353,ajdabiya,LY,71.10,74,0,8.39,30.7554,20.2263,1655525726,
372,saint anthony,US,70.93,70,0,0.00,45.0205,-93.2180,1655525733,
379,corinto,GR,75.88,60,0,2.82,37.9407,22.9573,1655525735,
387,mira,IT,72.10,75,0,3.44,45.4358,12.1348,1655525738,
413,mao,ES,72.16,94,0,3.44,39.8885,4.2658,1655525749,
441,bafra,TR,71.82,68,0,2.91,41.5678,35.9069,1655525760,
444,grand gaube,MU,72.37,75,0,3.00,-20.0064,57.6608,1655525762,

In [8]:
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

params = {
    "keyword": "hotel",
    "radius":  "5000",
    "key": g_key,
}

for index, row in hotel_df.iterrows():
    lat = row['Latitude']
    lng = row['Longitude']
    city = row['City']
    params['location'] = f"{lat},{lng}"

    response = requests.get(base_url, params=params).json()

    try:
        hotel_df.loc[index,"Hotel Name"] = response["results"][0]["name"]

    except: 
        hotel_df.loc[index, "Hotel Name"] = "NaN"

hotel_df

c:\Users\ronfu\anaconda3\envs\bootcamp\lib\site-packages\pandas\core\indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

,City,Country,Temperature,Humidity,Cloudiness,Windspeed,Latitude,Longitude,Date,Hotel Name
19,reidsville,US,70.48,100,0,0.00,36.3549,-79.6645,1655525598,"Holiday Inn Express & Suites Reidsville, an IH..."
37,saint-denis,FR,73.18,59,0,4.61,48.9167,2.3333,1655525522,HÃ´tel Grand Amour
40,souillac,MU,71.35,71,0,2.84,-20.5167,57.5167,1655525604,Shanti Maurice Resort & Spa
61,mahebourg,MU,72.25,73,0,1.07,-20.4081,57.7000,1655525612,Astroea Beach Mauritius
63,bethel,US,73.76,74,0,3.44,41.3712,-73.4140,1655525613,Hampton Inn Danbury
96,quatre cocos,MU,72.09,74,0,1.59,-20.2078,57.7625,1655525625,"Shangri-La Le Touessrok, Mauritius"
174,bambous virieux,MU,72.21,74,0,0.47,-20.3428,57.7575,1655525655,La Case du PÃªcheur
185,gat,IL,74.39,100,0,3.00,31.6100,34.7642,1655525660,Desert Gat
201,awjilah,LY,74.35,50,0,5.93,29.1081,21.2869,1655525667,NaN
208,jalu,LY,75.06,46,0,6.17,29.0331,21.5482,1655525669,Ø¥Ø³ØªØ±Ø§Ø­Ø© ØµÙ„Ø§Ø­ Ø§Ù„ØµØ§Ø¯Ù‚
233,conde,BR,71.06,100,0,3.44,-7.2597,-34.9075,1655525678,Paradise Inn Hummingbirds
242,urumqi,CN,74.35,29,0,4.47,43.8010,87.6005,1655525682,Sheraton Urumqi Hotel
265,hun,LY,70.63,54,0,3.60,29.1268,15.9477,1655525694,Al Nakhel Hotel
266,middle island,US,75.87,60,0,9.22,40.8843,-72.9373,1655525694,Home2 Suites by Hilton Long Island Brookhaven
268,kerman,IR,79.72,16,0,3.62,30.2832,57.0788,1655525695,Kerman Hotel
287,cap malheureux,MU,72.46,75,0,3.00,-19.9842,57.6142,1655525703,Coin de Mire Attitude Hotel
318,laurel,US,78.48,55,0,6.91,39.0993,-76.8483,1655525713,DoubleTree by Hilton Hotel Laurel
319,hamilton,US,74.64,58,0,9.22,39.1834,-84.5333,1655525421,Graduate Cincinnati
325,nador,MA,75.45,78,0,4.61,35.1740,-2.9287,1655525715,HÃ´tel Mercure Rif Nador
336,natal,BR,75.42,94,0,5.75,-5.7950,-35.2094,1655525719,Wish Natal
341,shahreza,IR,76.30,21,0,4.34,32.0339,51.8794,1655525721,Ø¨Ø§Øº Ø§Ø­Ø³Ø§Ù†
349,russell,US,79.12,88,0,0.00,32.3502,-85.1999,1655525724,NaN
353,ajdabiya,LY,71.10,74,0,8.39,30.7554,20.2263,1655525726,Ajdabiya Hotel
372,saint anthony,US,70.93,70,0,0.00,45.0205,-93.2180,1655525733,Hewing Hotel
379,corinto,GR,75.88,60,0,2.82,37.9407,22.9573,1655525735,Club Hotel Casino Loutraki
387,mira,IT,72.10,75,0,3.44,45.4358,12.1348,1655525738,Hotel Villa Franceschi
413,mao,ES,72.16,94,0,3.44,39.8885,4.2658,1655525749,BarcelÃ³ Hamilton Menorca - Adults Only
441,bafra,TR,71.82,68,0,2.91,41.5678,35.9069,1655525760,Sevgi Otel
444,grand gaube,MU,72.37,75,0,3.00,-20.0064,57.6608,1655525762,Veranda Paul et Virginie Hotel & Spa

In [9]:
# Drop NaN values
hotel_df = hotel_df[hotel_df["Hotel Name"].str.contains("NaN") == False]
# Rename columns
hotel_df = hotel_df.rename(columns={"Latitude": "Lat", "Longitude": "Lng"})
hotel_df

,City,Country,Temperature,Humidity,Cloudiness,Windspeed,Lat,Lng,Date,Hotel Name
19,reidsville,US,70.48,100,0,0.00,36.3549,-79.6645,1655525598,"Holiday Inn Express & Suites Reidsville, an IH..."
37,saint-denis,FR,73.18,59,0,4.61,48.9167,2.3333,1655525522,HÃ´tel Grand Amour
40,souillac,MU,71.35,71,0,2.84,-20.5167,57.5167,1655525604,Shanti Maurice Resort & Spa
61,mahebourg,MU,72.25,73,0,1.07,-20.4081,57.7000,1655525612,Astroea Beach Mauritius
63,bethel,US,73.76,74,0,3.44,41.3712,-73.4140,1655525613,Hampton Inn Danbury
96,quatre cocos,MU,72.09,74,0,1.59,-20.2078,57.7625,1655525625,"Shangri-La Le Touessrok, Mauritius"
174,bambous virieux,MU,72.21,74,0,0.47,-20.3428,57.7575,1655525655,La Case du PÃªcheur
185,gat,IL,74.39,100,0,3.00,31.6100,34.7642,1655525660,Desert Gat
208,jalu,LY,75.06,46,0,6.17,29.0331,21.5482,1655525669,Ø¥Ø³ØªØ±Ø§Ø­Ø© ØµÙ„Ø§Ø­ Ø§Ù„ØµØ§Ø¯Ù‚
233,conde,BR,71.06,100,0,3.44,-7.2597,-34.9075,1655525678,Paradise Inn Hummingbirds
242,urumqi,CN,74.35,29,0,4.47,43.8010,87.6005,1655525682,Sheraton Urumqi Hotel
265,hun,LY,70.63,54,0,3.60,29.1268,15.9477,1655525694,Al Nakhel Hotel
266,middle island,US,75.87,60,0,9.22,40.8843,-72.9373,1655525694,Home2 Suites by Hilton Long Island Brookhaven
268,kerman,IR,79.72,16,0,3.62,30.2832,57.0788,1655525695,Kerman Hotel
287,cap malheureux,MU,72.46,75,0,3.00,-19.9842,57.6142,1655525703,Coin de Mire Attitude Hotel
318,laurel,US,78.48,55,0,6.91,39.0993,-76.8483,1655525713,DoubleTree by Hilton Hotel Laurel
319,hamilton,US,74.64,58,0,9.22,39.1834,-84.5333,1655525421,Graduate Cincinnati
325,nador,MA,75.45,78,0,4.61,35.1740,-2.9287,1655525715,HÃ´tel Mercure Rif Nador
336,natal,BR,75.42,94,0,5.75,-5.7950,-35.2094,1655525719,Wish Natal
341,shahreza,IR,76.30,21,0,4.34,32.0339,51.8794,1655525721,Ø¨Ø§Øº Ø§Ø­Ø³Ø§Ù†
353,ajdabiya,LY,71.10,74,0,8.39,30.7554,20.2263,1655525726,Ajdabiya Hotel
372,saint anthony,US,70.93,70,0,0.00,45.0205,-93.2180,1655525733,Hewing Hotel
379,corinto,GR,75.88,60,0,2.82,37.9407,22.9573,1655525735,Club Hotel Casino Loutraki
387,mira,IT,72.10,75,0,3.44,45.4358,12.1348,1655525738,Hotel Villa Franceschi
413,mao,ES,72.16,94,0,3.44,39.8885,4.2658,1655525749,BarcelÃ³ Hamilton Menorca - Adults Only
441,bafra,TR,71.82,68,0,2.91,41.5678,35.9069,1655525760,Sevgi Otel
444,grand gaube,MU,72.37,75,0,3.00,-20.0064,57.6608,1655525762,Veranda Paul et Virginie Hotel & Spa

In [10]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [11]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(markers)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))